### ISSUE TITLE
Implement emojis ❤️

### ISSUE THREAD

**Issue by nikolaiwarner** [cabal-club/cabal-mobile#10]
Implement an emoji picker. This one seems nice: https://github.com/missive/emoji-mart

Also, we should consider the inline keyword emoji that github/slack provide .... like this :emoji: ... as that's a handy way to type emoji as well.

**Comment by vesparny** [comment]
In iOS there is a default emojii picker. I do not think there is the need of overriding the default platform behavior.
<img width="447" alt="screen shot 2018-06-25 at 10 50 59" src="https://user-images.githubusercontent.com/82070/41840386-e853912e-7865-11e8-90e6-81f236d0a946.png">

**Comment by soyuka** [comment]
It's the same on modern android also you have an embed emoji's keyboard.

**Comment by nikolaiwarner** [comment]
Yep! That'll do!
