### ISSUE TITLE
prettier + standard

### ISSUE THREAD

**Issue by vesparny** [cabal-club/cabal-mobile#24]
How about setting up prettier and standard for code formatting and linting?
It would avoid nitpicking and ensure consistency, especially for contributors.

I'd be happy to submit a PR, in case.

**Comment by soyuka** [comment]
standard is enough imo :+1:

**Comment by nikolaiwarner** [comment]
I snuck standard in as a dev dependency in #5. Is that enough? Or does it need more setup to be fully enforced?

**Comment by vesparny** [comment]
I normally use it paired with [lint-staged](https://github.com/okonet/lint-staged)

**Comment by soyuka** [comment]
@nikolaiwarner test should be `standard && jest` (https://github.com/cabal-club/cabal-mobile/blob/master/package.json#L10 )
